MuDuck-team/MuDuck

client/src/routes/Main/MainPage.jsx
client/src/routes/Main/PopularPlays.jsx
client/src/routes/Main/PopularPosts.jsx

- #56 
피그마를 참고해 메인 페이지 UI 구현했습니다.
임시로 더미 데이터를 사용해 개발했으며 추후 수정할 예정입니다.
인기글 추천과 추천 공연에 관한 코드를 분리한 게 괜찮을까요?
변수나 파일 이름 중 수정할 사항은 없을까요?(PopularPosts 등)

[Feat] Main 페이지 구현

---

client/src/components/DropDown.jsx

- #18 
```javascript
const handleOptionClick = option => {
setSelectedOption(option);
setIsOpen(false);
onClick(option.id);
};
```
에서
```javascript
const handleOptionClick = option => {
setSelectedOption(option);
setIsOpen(false);
onClick(option);
};
```
로 옵션 객체 전체를 다룰 수 있게 하였습니다.

[Refactor] 선택한 값을 id뿐 아니라 객체 전체를 받도록 변경

---

client/src/routes/Mypage/ContentData.js
client/src/routes/Mypage/MyPage.jsx

- #58 
페이지네이션 테스트를 위해 임시 데이터를 추가하고 마이페이지 UI를 구현했습니다.
현재 기본 UI만 완성된 상태이며 추후 서버 연결 시 기능 구현과 함께 수정할 예정입니다.
코드 양이 길어져 가독성이 떨어지는 것 같아 코드 분리가 필요한지 고민됩니다.

[Design] Mypage UI 구현

---

client/src/components/Header.jsx
client/src/components/ProfileImage/index.js
client/src/routes/Mypage/MyPage.jsx

[Fix] 파일 import path 수정

---

client/src/components/MeatballsMenu.jsx
client/src/components/PostInfo.jsx
client/src/routes/Notice/Notice.jsx

- #60 
공지사항 상세 페이지 UI를 개발했습니다. 미트볼 메뉴는 재사용될거라 생각해 별도로 컴포넌트로 분리했습니다.

[Design] 공지사항 상세 페이지 UI 구현

---

server/.gitignore
server/appspec.yml
server/scripts/deploy.sh
server/src/docs/asciidoc/index.adoc
server/src/main/java/MuDuck/MuDuck/board/controller/BoardController.java
server/src/main/java/MuDuck/MuDuck/board/entity/Board.java
server/src/main/java/MuDuck/MuDuck/board/mapper/BoardMapper.java
server/src/main/java/MuDuck/MuDuck/board/repository/BoardRepository.java
server/src/main/java/MuDuck/MuDuck/board/service/BoardService.java
server/src/main/java/MuDuck/MuDuck/boardCategory/entity/BoardCategory.java
server/src/main/java/MuDuck/MuDuck/boardCategory/repository/BoardCategoryRepository.java
server/src/main/java/MuDuck/MuDuck/category/entity/Category.java
server/src/main/java/MuDuck/MuDuck/category/repository/CategoryRepository.java
server/src/main/java/MuDuck/MuDuck/noticeboard/repository/NoticeBoardRepository.java
server/src/main/java/MuDuck/MuDuck/noticeboard/service/NoticeBoardService.java
server/src/main/resources/application-deploy.yml
server/src/main/resources/application.yml
server/src/main/resources/db/data.sql
server/src/main/resources/static/docs/index.html
server/src/test/java/MuDuck/MuDuck/board/controller/BoardControllerTest.java

CI/CD 설정 진행

---

server/src/test/java/MuDuck/MuDuck/MuDuckApplicationTests.java
server/src/test/resources/application.yml

CI/CD를 위한 설정 진행

---

client/src/routes/Error/ErrorPage.jsx

[Design] ErrorPage 디자인 추가

---

server/src/main/java/MuDuck/MuDuck/advice/GlobalExceptionAdvice.java
server/src/main/java/MuDuck/MuDuck/auth/handler/OAuth2AuthenticationSuccessHandler.java
server/src/main/java/MuDuck/MuDuck/exception/ExceptionCode.java
server/src/main/java/MuDuck/MuDuck/member/controller/MemberController.java
server/src/main/java/MuDuck/MuDuck/member/dto/MemberDto.java
server/src/main/java/MuDuck/MuDuck/response/ErrorResponse.java
server/src/main/java/MuDuck/MuDuck/token/service/RefreshTokenService.java

#37 
회원 API 명세서 구현 및 ErrorReponse 추가 , OAuth2 RedirectURL 변경
URL 전역변수 변경하는 것을 고민해봐야겠다.

[Feat/Fix] 회원 컨트롤러 API 구현 및 ErrorResponse 추가 & OAuth2 핸들러 URL 변경

---

server/src/main/java/MuDuck/MuDuck/member/controller/MemberController.java
server/src/main/java/MuDuck/MuDuck/member/mapper/MemberMapper.java
server/src/main/java/MuDuck/MuDuck/member/service/MemberService.java

[Fix] 회원정보수정API 수정

---

server/src/docs/asciidoc/index.adoc
server/src/main/java/MuDuck/MuDuck/board/controller/BoardController.java
server/src/main/java/MuDuck/MuDuck/board/entity/Board.java
server/src/main/java/MuDuck/MuDuck/boardCategory/service/BoardCategoryService.java
server/src/main/resources/application.yml
server/src/test/java/MuDuck/MuDuck/board/controller/BoardControllerTest.java

#36 
게시판 API 명세서 9번 구현
POST /board/writing
Controller Test만 진행한 상태다. Service Test도 진행해야한다.

[Feat] 게시판 API 명세서 9번 #36

---

server/.gitignore
server/src/docs/asciidoc/index.adoc
server/src/main/java/MuDuck/MuDuck/board/controller/BoardController.java
server/src/main/java/MuDuck/MuDuck/board/dto/BoardDto.java
server/src/main/java/MuDuck/MuDuck/board/mapper/BoardMapper.java
server/src/main/java/MuDuck/MuDuck/board/service/BoardService.java
server/src/main/java/MuDuck/MuDuck/exception/ExceptionCode.java
server/src/main/resources/db/data.sql
server/src/test/java/MuDuck/MuDuck/board/controller/BoardControllerTest.java

#36 
게시글 수정 및 삭제 테스트 구현
각 테스트에 DisplayName 추가
queryParameter에 대한 Optional을 표시해줄 방법에 대해서 고민
mapper 테스트도 추가해야한다.

[Test] 게시글 수정 및 삭제 테스트 구현

---

server/src/docs/asciidoc/index.adoc
server/src/test/java/MuDuck/MuDuck/board/controller/BoardControllerTest.java

#36 
index.adoc 파일 patchBoard 누락 내용 추가

[Doc] index.adoc 파일 patchBoard 누락 내용 추가   #36

---

server/src/main/java/MuDuck/MuDuck/advice/GlobalExceptionAdvice.java
server/src/main/java/MuDuck/MuDuck/auth/config/SecurityConfiguration.java
server/src/main/java/MuDuck/MuDuck/exception/ExceptionCode.java
server/src/main/java/MuDuck/MuDuck/map/repository/MapRepository.java
server/src/main/java/MuDuck/MuDuck/recommendplace/repository/RecommendPlaceRepository.java
server/src/main/java/MuDuck/MuDuck/token/controller/RefreshTokenController.java
server/src/main/resources/db/data.sql

…handler 추가
#37 
1. 주변장소추천, 지도 관련 repository 생성
2. security cors 쪽 s3 주소로 변경
3. controller에서 cookie 가 없을 경우 exceptionHandler 추가
해당 컨트롤러 테스트도 필요보인다.

[Feat/Fix] 주변장소추천 , 지도 repository 생성 및 security cors 설정 수정, exceptiohandler 추가

---

server/src/main/java/MuDuck/MuDuck/board/controller/BoardController.java
server/src/main/java/MuDuck/MuDuck/board/dto/BoardDto.java
server/src/main/java/MuDuck/MuDuck/board/mapper/BoardMapper.java
server/src/main/java/MuDuck/MuDuck/comment/dto/CommentDto.java
server/src/main/java/MuDuck/MuDuck/comment/entity/Comment.java
server/src/main/java/MuDuck/MuDuck/comment/mapper/CommentMapper.java
server/src/main/java/MuDuck/MuDuck/comment/service/CommentService.java
server/src/main/java/MuDuck/MuDuck/exception/ExceptionCode.java
server/src/main/resources/db/data.sql
server/src/test/java/MuDuck/MuDuck/board/controller/BoardControllerTest.java

#36 
게시글 불러올 때 ResponseBody에 게시글 및 댓글 작성자의 ID 반환하는 것을 추가함

[Fix] 게시글 불러올 때 게시글 및 댓글 작성자의 ID 반환하는 것을 추가함

---

server/src/main/java/MuDuck/MuDuck/exception/ExceptionCode.java

#36 
Merge 하던 중 Conflict 파일을 잘못 해결해서 생긴 오류 수정

[Fix] Merge 하던 중 Conflict 파일을 잘못 해결해서 생긴 오류 수정 #36

---

server/src/main/java/MuDuck/MuDuck/auth/handler/OAuth2AuthenticationSuccessHandler.java
server/src/main/resources/db/data.sql

#37 
1. 더미데이터 추가
2. cookie 설정 변경
http여서 안되는 건지 궁금하다..

[Fix] 더미데이터 추가 및 테스트를 위한 cookie 설정 변경

---

server/src/main/java/MuDuck/MuDuck/board/controller/BoardController.java
server/src/test/java/MuDuck/MuDuck/board/controller/BoardControllerTest.java

#36 
[Fix] 게시글 요청 End Point 수정

[Fix] 게시글 요청 End Point 수정 #36

---

server/src/main/java/MuDuck/MuDuck/auth/handler/OAuth2AuthenticationSuccessHandler.java
server/src/main/resources/application.yml

#37 
1. cookie 설정 원래 상태로 변경
2. 액세스 토큰 유효기간 하루로 변경
https를 붙인 다음 한번더 테스트가 필요해 보인다.

[Fix] cookie 설정 원래 상태로 변경 및 액세스토큰 유효기간 변경

---

server/src/main/java/MuDuck/MuDuck/auth/config/SecurityConfiguration.java
server/src/main/java/MuDuck/MuDuck/map/repository/MapRepository.java
server/src/main/resources/db/data.sql

#37 
1. 더미데이터 추가
2. security cors 설정 변경

[Fix] mapRepository 수정및 더미데이터 수정 security cors 설정 변경

---

server/src/docs/asciidoc/index.adoc
server/src/main/java/MuDuck/MuDuck/board/controller/BoardController.java
server/src/main/java/MuDuck/MuDuck/board/service/BoardService.java
server/src/test/java/MuDuck/MuDuck/board/controller/BoardControllerTest.java

#36 
댓글 post responseBody를 HttpStatus로만 응답하도록 변경 또한 해당 사항에 맞게 Controller Test 코드 구현

[Refact] 댓글 post responseBody를 HttpStatus로만 응답하도록 변경 또한 해당 사항에 맞게 Controller Test 코드 구현

---

server/src/docs/asciidoc/index.adoc
server/src/main/java/MuDuck/MuDuck/board/controller/BoardController.java
server/src/main/java/MuDuck/MuDuck/board/service/BoardService.java
server/src/test/java/MuDuck/MuDuck/board/controller/BoardControllerTest.java

#36 
게시글 Patch ResponseBody를 HttpStatus로만 응답하도록 변경, 해당 사항에 맞게 Test 코드 수정 완료

[Refact] 게시글 Patch ResponseBody를 HttpStatus로만 응답하도록 변경, 해당 사항에 맞게 Test 코드 수정 완료

---

server/src/docs/asciidoc/index.adoc
server/src/main/java/MuDuck/MuDuck/board/controller/BoardController.java
server/src/test/java/MuDuck/MuDuck/board/controller/BoardControllerTest.java

#36 
대댓글 post responseBody를 HttpStatus로만 응답하도록 변경 관련 Controller Test 작성

[Refact] 대댓글 post responseBody를 HttpStatus로만 응답하도록 변경 관련 Controller Test 작성

---

server/src/docs/asciidoc/index.adoc
server/src/main/java/MuDuck/MuDuck/board/controller/BoardController.java
server/src/test/java/MuDuck/MuDuck/board/controller/BoardControllerTest.java

#36 
댓글 delete 코드 responseBody를 HttpStatus로만 응답하게 변경 및 테스트 코드 구현

[Refact/Test] 댓글 delete 코드 responseBody를 HttpStatus로만 응답하게 변경 및 테스트 코드 구현

---

client/src/components/Header.jsx

#116 
모바일사이즈에서 헤더 토글이 열렸을 때, 링크를 클릭하면 헤더가 안닫히는 현상 보완
주변시설 라우팅 대표 극장아이디 대표1번으로 수정

[Feat] 모바일 사이즈에서 탭클릭시 헤더토글 닫기 기능 추가

---

client/public/index.html
client/src/components/Cards.jsx
client/src/routes/Posts/PostsPage.jsx

- #54 
완성된 ui에 서버에서 데이터를 불러와 뿌려주는 기능을 만들었습니다.
파라미터들이 변경된 부분들이 있어 바꿔주었습니다.
script에 async를 붙이라는 에러가 나와 붙여주었습니다.
로그인 안된 상태에서 작성하기를 눌렀을 때 어떤 처리를 해주어야 할지 고민해보아야 할 것 같습니다.

[Frontend] Feature/posts get data 구현

---

server/src/docs/asciidoc/index.adoc
server/src/main/java/MuDuck/MuDuck/board/controller/BoardController.java
server/src/main/java/MuDuck/MuDuck/board/entity/Board.java
server/src/main/java/MuDuck/MuDuck/board/service/BoardService.java
server/src/main/java/MuDuck/MuDuck/boardLike/entity/BoardLike.java
server/src/main/java/MuDuck/MuDuck/boardLike/repository/BoardLikeRepository.java
server/src/main/java/MuDuck/MuDuck/exception/ExceptionCode.java
server/src/test/java/MuDuck/MuDuck/board/controller/BoardControllerTest.java

#36 
게시글 좋아요 기능 구현 및 Controller Test 구현 완료

[Feat] 게시글 좋아요 기능 구현 및 Controller Test 구현 완료

---

server/src/docs/asciidoc/index.adoc
server/src/main/java/MuDuck/MuDuck/map/controller/MapController.java
server/src/main/java/MuDuck/MuDuck/map/dto/AvgDto.java
server/src/main/java/MuDuck/MuDuck/map/entity/AvgEntity.java
server/src/main/java/MuDuck/MuDuck/map/groupcode/GroupCode.java
server/src/main/java/MuDuck/MuDuck/map/mapper/MapMapper.java
server/src/main/java/MuDuck/MuDuck/map/repository/MapRepository.java
server/src/main/java/MuDuck/MuDuck/map/service/MapService.java
server/src/main/resources/db/data.sql
server/src/test/java/MuDuck/MuDuck/map/controller/MapControllerTest.java

#37 
1. 평균 별점과 총 리뷰수가 합쳐진 지도정보 조회 API 코드 구현
2. 1번 내용에 대한 테스트 코드 작성
3. GroupCode name 수정
4. theaterId 를 2로 가지는 더미데이터 추가

[Feat/Fix] 지도정보 조회 API 코드 구현 및 테스트 코드 구현 & GroupCode 수정 & 더미 데이터 추가

---

server/src/main/java/MuDuck/MuDuck/musical/controller/MusicalController.java
server/src/main/java/MuDuck/MuDuck/musical/dto/ActorMusicalResponseDto.java
server/src/main/java/MuDuck/MuDuck/musical/dto/MusicalDto.java
server/src/main/java/MuDuck/MuDuck/musical/entity/Musical.java
server/src/main/java/MuDuck/MuDuck/musical/mapper/MusicalMapper.java
server/src/main/java/MuDuck/MuDuck/musical/repository/MusicalRepository.java
server/src/main/java/MuDuck/MuDuck/musical/service/MusicalService.java
server/src/main/java/MuDuck/MuDuck/theater/dto/TheaterDto.java
server/src/main/java/MuDuck/MuDuck/theater/mapper/TheaterMapper.java
server/src/main/resources/application.yml
server/src/main/resources/db/data.sql
server/src/test/java/MuDuck/MuDuck/musical/controller/MusicalControllerMockTest.java

#38
Musical Api #5 Controller구현 및 Test 케이스 작성, category 테이블 생성 쿼리 변경 및 쿼리 순서 변경
Musical API #1~#4 refactoring, Musical API #6,7 구현 중 이슈해결

[Feat/Fix] Musical Api #5 Controller구현 및 Test 케이스 작성, category 테이블 생성 쿼리 변경 및 쿼리 순서 변경 #38

---

server/src/main/java/MuDuck/MuDuck/musical/controller/MusicalController.java
server/src/main/java/MuDuck/MuDuck/musical/dto/MusicalDto.java
server/src/main/java/MuDuck/MuDuck/musical/dto/MusicalPatchDto.java
server/src/main/java/MuDuck/MuDuck/musical/dto/MusicalPostDto.java
server/src/main/java/MuDuck/MuDuck/musical/dto/MusicalResponseDto.java
server/src/main/java/MuDuck/MuDuck/musical/entity/Musical.java
server/src/main/java/MuDuck/MuDuck/musical/mapper/MusicalMapper.java
server/src/main/java/MuDuck/MuDuck/musical/repository/MusicalRepository.java
server/src/main/java/MuDuck/MuDuck/musical/service/MusicalService.java
server/src/main/resources/application.yml
server/src/test/java/MuDuck/MuDuck/musical/controller/MusicalControllerMockTest.java

#38
Musical Api #7 Controller구현 및 Test 케이스 작성
Refactoring 및 Musical Api #6 구현

[Feat] Musical Api #7 Controller구현 및 Test 케이스 작성 #38

---

server/src/docs/asciidoc/index.adoc
server/src/main/java/MuDuck/MuDuck/board/controller/BoardController.java
server/src/main/java/MuDuck/MuDuck/board/entity/Board.java
server/src/main/java/MuDuck/MuDuck/board/mapper/BoardMapper.java
server/src/main/java/MuDuck/MuDuck/board/service/BoardService.java
server/src/main/java/MuDuck/MuDuck/boardLike/repository/BoardLikeRepository.java
server/src/main/java/MuDuck/MuDuck/comment/dto/CommentDto.java
server/src/main/java/MuDuck/MuDuck/comment/mapper/CommentMapper.java
server/src/main/java/MuDuck/MuDuck/exception/ExceptionCode.java
server/src/test/java/MuDuck/MuDuck/board/controller/BoardControllerTest.java

#36 
게시글 좋아요 삭제 기능 구현 및 Controller Test 진행

[Feat/Test] 게시글 좋아요 삭제 기능 구현 및 Controller Test 진행

---

server/src/docs/asciidoc/index.adoc
server/src/main/java/MuDuck/MuDuck/musical/dto/Category.java
server/src/main/java/MuDuck/MuDuck/musical/dto/MusicalBoards.java
server/src/test/java/MuDuck/MuDuck/MuDuckApplicationTests.java
server/src/test/java/MuDuck/MuDuck/musical/controller/MusicalControllerMockTest.java

#38
누락된 파일 첨부 및 코드수정
contextLoad 에러 잡기

[Fix] Musical Api #7 Controller구현 및 Test 케이스 작성 #38

---

client/src/components/Button.jsx
client/src/components/WriterInfo.jsx
client/src/index.jsx
client/src/routes/Post/CommentList.jsx
client/src/routes/Post/PostPage.jsx

- #60 
커뮤니티 상세 페이지 댓글 등록/삭제 기능을 1차적으로 구현했습니다.
댓글 상태에 대한 정보를 받아 삭제된 댓글에 대한 처리도 추가할 예정입니다.
반복되는 코드가 여럿 있어 개선이 필요할 듯 합니다.

[Feat] 커뮤니티 상세 페이지 댓글 등록/삭제 기능 구현

---

client/src/components/Editors.jsx
client/src/index.jsx
client/src/routes/Nearby/NearbyPage.jsx
client/src/routes/PostAdd/PostAddPage.jsx
client/src/routes/PostEdit/PostEditPage.jsx

- #53 
게시물을 작성하고, 수정하는 페이지를 만들었습니다,
edit 페이지에선 사용자가 주소를 접근할 것을 생각해 
게시물의 publisherId와, 사용자의 id가 다른 경우 이전 페이지로 이동하게 만들었습니다.
axios를 사용할 때 네트워크 에러가 발생해도 catch문으로 넘어 가지를 않아 에러 핸들링이 불가능합니다. 우선 try catch문으로 해놓았는데 후에 수정이 필요합니다.

[Feat] Feature/post add update

---

client/src/components/ProfileImage/ProfileImgSetter.jsx
client/src/routes/Login/LoginPage.jsx
client/src/routes/Myinfo/MyinfoPage.jsx
client/src/routes/Mypage/MyPage.jsx

#128 
#129
- 마이페이지 프로필세터 기능을 구현 : 기존 프로필 사진을 클릭하고 변경한 다음 변경사항적용하기 버튼을 누르면 프로필이 변경됩니다.
- 닉네임 변경기능 구현 : 유저가 닉네임을 변경할 수 있습니다.

[Feat] mypage 프로필사진 닉네임 변경기능 구현

---

client/src/routes/Posts/PostsPage.jsx

- #54 
헤더에서 자신의 페이지를 선택했을 때 
드롭다운에서 선택했던 것들을 다시 초기화 시켜줬습니다.

[Feat] 헤더에서 자신의 페이지를 눌렀을 때 선택한 드롭다운 값이 초기화되게 함

---

server/src/docs/asciidoc/index.adoc
server/src/main/java/MuDuck/MuDuck/actor/dto/ActorDto.java
server/src/main/java/MuDuck/MuDuck/actorMusical/entity/ActorsEntity.java
server/src/main/java/MuDuck/MuDuck/actorMusical/mapper/ActorMusicalMapper.java
server/src/main/java/MuDuck/MuDuck/actorMusical/repository/ActorMusicalRepository.java
server/src/main/java/MuDuck/MuDuck/actorMusical/service/ActorMusicalService.java
server/src/main/java/MuDuck/MuDuck/exception/ExceptionCode.java
server/src/main/java/MuDuck/MuDuck/musical/controller/MusicalController.java
server/src/main/java/MuDuck/MuDuck/musical/dto/ActorMusicalResponseDto.java
server/src/main/java/MuDuck/MuDuck/musical/dto/CategoryDto.java
server/src/main/java/MuDuck/MuDuck/musical/dto/MusicalBoardsDto.java
server/src/main/java/MuDuck/MuDuck/musical/dto/MusicalDto.java
server/src/main/java/MuDuck/MuDuck/musical/entity/ActorMusical.java
server/src/main/java/MuDuck/MuDuck/musical/entity/Category.java
server/src/main/java/MuDuck/MuDuck/musical/entity/Musical.java
server/src/main/java/MuDuck/MuDuck/musical/entity/MusicalBoards.java
server/src/main/java/MuDuck/MuDuck/musical/mapper/MusicalMapper.java
server/src/main/java/MuDuck/MuDuck/musical/repository/MusicalRepository.java
server/src/main/java/MuDuck/MuDuck/musical/service/MusicalService.java
server/src/main/resources/db/data.sql
server/src/test/java/MuDuck/MuDuck/MuDuckApplicationTests.java
server/src/test/java/MuDuck/MuDuck/musical/controller/MusicalControllerMockTest.java
server/src/test/java/MuDuck/MuDuck/musical/service/MusicalServiceMockTest.java

#38
Musical Api #5 기능 개선 및 #7 관련 버그 수정
Musical Api #6 구현 및 값 전달 방식에 대한 고민

[FIX] Musical Api #5, #7 관련 버그 수정 #38

---

server/src/docs/asciidoc/index.adoc
server/src/main/java/MuDuck/MuDuck/board/repository/BoardRepository.java
server/src/main/java/MuDuck/MuDuck/board/service/BoardService.java
server/src/main/java/MuDuck/MuDuck/mainPage/controller/MainPageController.java
server/src/main/java/MuDuck/MuDuck/mainPage/dto/MainPageDto.java
server/src/main/java/MuDuck/MuDuck/mainPage/mapper/MainPageMapper.java
server/src/main/resources/db/data.sql
server/src/test/java/MuDuck/MuDuck/mainPage/controller/MainPageControllerTest.java

#134 
메인페이지 데일리, 위클리 인기글 기능 구현 및 Controller Test 진행
인기글의 기준은 좋아요로 진행하였다.

[Feat/Test] 메인페이지 데일리, 위클리 인기글 기능 구현 및 Controller Test 진행 #134

---

server/src/main/java/MuDuck/MuDuck/board/repository/BoardRepository.java
server/src/main/java/MuDuck/MuDuck/board/service/BoardService.java
server/src/main/java/MuDuck/MuDuck/boardLike/repository/BoardLikeRepository.java
server/src/main/java/MuDuck/MuDuck/myPage/controller/MyPageController.java
server/src/main/java/MuDuck/MuDuck/myPage/dto/MyPageDto.java
server/src/main/java/MuDuck/MuDuck/myPage/mapper/MyPageMapper.java
server/src/main/resources/db/data.sql

… 게시글 목록 가져올 때, 삭제된 게시글도 가져오는 에러 수정 완료.
#136 
[Feat/Fix] MyPage 내가 쓴 글 가져오기, 내가 좋아요 누른 글 가져오기 구현 완료. 카테고리네임에 값을 넣어서 게시글 목록 가져올 때, 삭제된 게시글도 가져오는 에러 수정 완료.

[Feat/Fix] MyPage 내가 쓴 글 가져오기, 내가 좋아요 누른 글 가져오기 구현 완료. 카테고리네임에 값을 넣어서 게시글 목록 가져올 때, 삭제된 게시글도 가져오는 에러 수정 완료.

---

server/src/docs/asciidoc/index.adoc
server/src/main/java/MuDuck/MuDuck/auth/config/SecurityConfiguration.java
server/src/main/java/MuDuck/MuDuck/exception/ExceptionCode.java
server/src/main/java/MuDuck/MuDuck/map/dto/MapDto.java
server/src/main/java/MuDuck/MuDuck/map/mapper/MapMapper.java
server/src/main/java/MuDuck/MuDuck/map/repository/MapRepository.java
server/src/main/java/MuDuck/MuDuck/map/service/MapService.java
server/src/main/java/MuDuck/MuDuck/member/service/MemberService.java
server/src/main/java/MuDuck/MuDuck/recommendplace/controller/RecommendPlaceController.java
server/src/main/java/MuDuck/MuDuck/recommendplace/dto/RecommendPlaceDto.java
server/src/main/java/MuDuck/MuDuck/recommendplace/mapper/RecommendPlaceMapper.java
server/src/main/java/MuDuck/MuDuck/recommendplace/repository/RecommendPlaceRepository.java
server/src/main/java/MuDuck/MuDuck/recommendplace/service/RecommendPlaceService.java
server/src/main/java/MuDuck/MuDuck/theater/service/TheaterService.java
server/src/main/resources/db/data.sql
server/src/test/java/MuDuck/MuDuck/member/controller/MemberControllerTest.java
server/src/test/java/MuDuck/MuDuck/recommendplace/controller/RecommendPlaceControllerTest.java
server/src/test/java/MuDuck/MuDuck/theater/controller/TheaterControllerTest.java

#37 
1. 한줄 평 과 별점 등록 API 구현
2. 1번 테스트코드 구현
3. 지도 정보 더미데이터 좌표 수정
4. 전체 극장 조회 API 정렬 기준 asc로 수정
주소 정규식에 대한 고민

[Feat/Fix] 한줄평과 별점 등록 API 구현및 테스트코드 구현 & 더미데이터 좌표 수정

---

server/src/docs/asciidoc/index.adoc
server/src/main/java/MuDuck/MuDuck/comment/repository/CommentRepository.java
server/src/main/java/MuDuck/MuDuck/comment/service/CommentService.java
server/src/main/java/MuDuck/MuDuck/myPage/controller/MyPageController.java
server/src/main/java/MuDuck/MuDuck/myPage/dto/MyPageDto.java
server/src/main/java/MuDuck/MuDuck/myPage/mapper/MyPageMapper.java
server/src/test/java/MuDuck/MuDuck/myPage/controller/MyPageControllerTest.java

#134 
내가 쓴 댓글 가져오기 기능 구현, MyPage 관련 Controller Test 완료

[Feat/Test] 내가 쓴 댓글 가져오기 기능 구현, MyPage 관련 Controller Test 완료

---

server/src/main/java/MuDuck/MuDuck/actor/mapper/ActorMapper.java
server/src/main/java/MuDuck/MuDuck/actorMusical/entity/ActorsEntity.java
server/src/main/java/MuDuck/MuDuck/actorMusical/entity/MusicalEntity.java
server/src/main/java/MuDuck/MuDuck/actorMusical/mapper/ActorMusicalMapper.java
server/src/main/java/MuDuck/MuDuck/actorMusical/repository/ActorMusicalRepository.java
server/src/main/java/MuDuck/MuDuck/actorMusical/service/ActorMusicalService.java
server/src/main/java/MuDuck/MuDuck/musical/controller/MusicalController.java
server/src/main/java/MuDuck/MuDuck/musical/dto/ActorMusicalDto.java
server/src/main/java/MuDuck/MuDuck/musical/dto/MusicalDto.java
server/src/main/java/MuDuck/MuDuck/musical/entity/ActorMusical.java
server/src/main/java/MuDuck/MuDuck/musical/entity/ActorMusicalEntity.java
server/src/main/java/MuDuck/MuDuck/musical/entity/MusicalBoards.java
server/src/main/java/MuDuck/MuDuck/musical/entity/Response.java
server/src/main/java/MuDuck/MuDuck/musical/mapper/MusicalMapper.java
server/src/main/java/MuDuck/MuDuck/musical/repository/MusicalRepository.java
server/src/main/java/MuDuck/MuDuck/musical/service/MusicalService.java
server/src/test/java/MuDuck/MuDuck/musical/controller/MusicalControllerMockTest.java

#38
Musical Api #6 Controller구현 완료 및 테스트코드 작성 중, #7 Response추가
디버깅 및 Refactring, comment갯수 response하기

[FEAT/FIX] Musical Api #6 Controller구현 완료 및 테스트코드 작성 중, #7 Response추가 #38

---

server/src/docs/asciidoc/index.adoc
server/src/main/java/MuDuck/MuDuck/map/service/MapService.java
server/src/main/java/MuDuck/MuDuck/recommendplace/controller/RecommendPlaceController.java
server/src/main/java/MuDuck/MuDuck/recommendplace/repository/RecommendPlaceRepository.java
server/src/main/java/MuDuck/MuDuck/recommendplace/service/RecommendPlaceService.java
server/src/test/java/MuDuck/MuDuck/map/controller/MapControllerTest.java
server/src/test/java/MuDuck/MuDuck/member/controller/MemberControllerTest.java
server/src/test/java/MuDuck/MuDuck/recommendplace/controller/RecommendPlaceControllerTest.java

#37
1. 평점과 한줄평 조회 API 구현
2. 1번 테스트 코드 구현
3. rest docs path-parameters 확인 가능하게 수정
service 클래스 및 repository 클래스 테스트 코드도 구현이 필요해보인다.

[Feat/Fix] 평점과 한줄평 조회API 구현 및 테스트 코드 구현 & rest docs 수정

---

server/src/main/java/MuDuck/MuDuck/board/mapper/BoardMapper.java
server/src/main/java/MuDuck/MuDuck/board/repository/BoardRepository.java
server/src/main/java/MuDuck/MuDuck/board/service/BoardService.java
server/src/main/java/MuDuck/MuDuck/boardLike/repository/BoardLikeRepository.java
server/src/main/java/MuDuck/MuDuck/comment/repository/CommentRepository.java
server/src/main/java/MuDuck/MuDuck/comment/service/CommentService.java
server/src/main/java/MuDuck/MuDuck/myPage/controller/MyPageController.java
server/src/main/java/MuDuck/MuDuck/response/MyPageBoardMultipleResponse.java
server/src/main/java/MuDuck/MuDuck/response/MyPageCommentsMultipleResponse.java

#134
마이페이지 기능에 페이지네이션을 추가했습니다.

[Fix] 마이페이지 기능에 페이지네이션 적용 #134

---

server/src/test/java/MuDuck/MuDuck/myPage/controller/MyPageControllerTest.java

#134 
[Fix] 마이페이지 Controller Test 주석 처리 #134

[Fix] 마이페이지 Controller Test 주석 처리 #134

---

client/src/components/Input.jsx
client/src/components/MeatballsMenu.jsx
client/src/components/WriterInfo.jsx
client/src/routes/Post/CommentList.jsx
client/src/routes/Post/PostPage.jsx

- #60
- #121
커뮤니티 상세 페이지 기능을 구현했습니다.
추후 모달 디자인 수정이 필요할 것 같습니다.

[Feat] 커뮤니티 상세 페이지 기능 구현

---

server/src/docs/asciidoc/index.adoc
server/src/main/java/MuDuck/MuDuck/recommendplace/controller/RecommendPlaceController.java
server/src/main/java/MuDuck/MuDuck/recommendplace/dto/RecommendPlaceDto.java
server/src/main/java/MuDuck/MuDuck/recommendplace/mapper/RecommendPlaceMapper.java
server/src/main/java/MuDuck/MuDuck/recommendplace/service/RecommendPlaceService.java
server/src/test/java/MuDuck/MuDuck/recommendplace/controller/RecommendPlaceControllerTest.java

#37 
1. 평점 및 한줄평 수정 API 구현
2. 1번 테스트 코드 구현 
예외처리 테스트코드 구현이 필요하다.

[Feat] 평점 및 한줄평 수정 API 구현 및 테스트 코드 구현

---

server/src/test/java/MuDuck/MuDuck/myPage/controller/MyPageControllerTest.java

#134 
마이페이지 페이지네이션 구현에 따른 Controller Test 변경

[Test] 마이페이지 페이지네이션 구현에 따른 Controller Test 변경 #134

---

client/src/components/ProfileImage/ProfileImgSetter.jsx
client/src/routes/Myinfo/MyinfoPage.jsx

- #131 
유저가 카카오로그인 선택시 아무런 반응이 없는 것 처럼 보여서 업로드 카드에 음영 어둡게 처리

[Design] 카카오로그인선택시 업로드아이콘 배경 어둡게 처리

---

server/src/main/java/MuDuck/MuDuck/board/dto/BoardDto.java
server/src/main/java/MuDuck/MuDuck/board/mapper/BoardMapper.java
server/src/main/java/MuDuck/MuDuck/board/repository/BoardRepository.java
server/src/main/java/MuDuck/MuDuck/musical/controller/MusicalController.java
server/src/main/java/MuDuck/MuDuck/musical/dto/MusicalDto.java
server/src/main/java/MuDuck/MuDuck/musical/entity/Musical.java
server/src/main/java/MuDuck/MuDuck/musical/mapper/MusicalMapper.java
server/src/main/java/MuDuck/MuDuck/musical/service/MusicalService.java
server/src/main/resources/db/data.sql

#38
Musical Api 7번 게시판 ID, 및 게시글 제목 빠져있는 이슈 수정
데모데이터 작성 및 Controller테스트 코드 작성

[FIX] Musical Api #7 이슈 수정 #38

---

server/src/main/java/MuDuck/MuDuck/comment/repository/CommentRepository.java

#134 
마이페이지 내가 쓴 댓글 가져오기 JPA 멤버아이디 변수로 설정해야하는데 안한거 수정

[Fix] 마이페이지 내가 쓴 댓글 가져오기 JPA 멤버아이디 변수로 설정해야하는데 안한거 수정 #134

---

server/src/test/java/MuDuck/MuDuck/recommendplace/controller/RecommendPlaceControllerTest.java

#37 
1. 평점 한줄평 Controller exception test 코드 구현
나머지 service 테스트 코드도 필요해보이다.

[TEST] 평점 한줄평exception 테스트 코드 구현

---

client/src/routes/Play/PlayPage.jsx

- #51 
공연상세 게시판 응답데이터의 필드명변경이 있어서 접근키를 수정하였습니다.

[Style] 공연상세 게시판 관련 응답데이터 필드명변경에 따른 조정

---

client/src/routes/Login/LoginPage.jsx

[Chore] 로그인페이지 원본으로 복구

---

client/src/routes/Nearby/NearbyPage.jsx

- #52 
로그인 해야만 볼 수 있는 버그가 있어 수정

[Fix] 로그인 해야만 볼 수 있는 버그

---

client/src/routes/Play/PlayPage.jsx

- #51
빈 데이터를 받아왔을 때 초기화를 해주지 못한 오류가 발생하여 해결했습니다.

[Fix] 빈배열 오류

---

client/src/api/muduckApi.js
client/src/routes/Nearby/NearbyPage.jsx
client/src/routes/Play/PlayPage.jsx

- #51 
useEffect 대신 loader 를 사용하여 데이터를 불러오게 했습니다.

[Fix] Feature/nearby page

---

client/src/components/Header.jsx
client/src/routes/OauthRedirect/OauthRedirectPage.jsx

[Fix] 페이지 첫 진입시 헤더 로그인상태로 되는 버그 수정

---

client/src/routes/PostAdd/PostAddPage.jsx

- #53 
게시글 작성페이지에서 로그인이 되지 않은 상태라면 로그인 페이지로 이동하게 만들었습니다.

[Feat] 게시물 작성 로그인 확인

---

client/src/components/Header.jsx
client/src/routes/OauthRedirect/OauthRedirectPage.jsx

[Fix] 헤더 새로고침시 유저정보 변경되는 버그 수정

---

client/src/components/ScrollToTop.jsx
client/src/routes/Root.jsx

[Feat] 로딩 & 스크롤 최상단 이동 기능 구현

---

server/src/main/java/MuDuck/MuDuck/recommendplace/controller/RecommendPlaceController.java
server/src/test/java/MuDuck/MuDuck/recommendplace/controller/RecommendPlaceControllerTest.java

#37 
1. 평점 및 한줄평 조회 API 수정
2. 1번 테스트 코드 수정

[Fix] 평점 및 한줄평 조회API 수정 및 테스트코드 수정

---

server/src/test/java/MuDuck/MuDuck/recommendplace/controller/RecommendPlaceControllerTest.java

[Fix] 평점 및 한줄평 조회 테스트코드 수정

---

client/src/components/Header.jsx

[Fix] 헤더 로그인 새로고침해야 반영되는 현상 수정

---

client/src/components/Loading.jsx

- #7 
Loading Spinner 크기를 조정했습니다.

[Design] Loading Spinner 크기 조정

---

client/src/components/Header.jsx
client/src/routes/Root.jsx

[Fix] 로그인 여부확인 헤더에서 Root로 변경

---

server/build.gradle
server/src/main/java/MuDuck/MuDuck/board/repository/BoardRepository.java
server/src/main/resources/application-local.yml
server/src/test/resources/application-local.yml
server/src/test/resources/application.yml

[Fix] MySQL 설정 완료

---

server/src/test/java/MuDuck/MuDuck/theater/repository/TheaterRepositoryTest.java
server/src/test/resources/application.yml

[Fix] MySQL 연결 후 Repository Test에 생기는 오류를 주석처리함 #134

---

client/src/routes/Notices/NoticesPage.jsx

[Fix] Feature/online edit get 공지사항 에러 수정

---

server/src/main/java/MuDuck/MuDuck/map/repository/MapRepository.java
server/src/test/java/MuDuck/MuDuck/theater/repository/TheaterRepositoryTest.java

#37 
1. mapRepository Mysql에 맞게 쿼리문 수정
2. theaterRepository Test 주석처리

[Fix] mapRepository Mysql에 맞게 쿼리문 수정

---

client/src/components/ImageCard.jsx
client/src/routes/Main/PopularPlays.jsx
client/src/routes/Plays/PlaysPage.jsx

- #14 
추후 API 개발 시 다시 추가할 예정입니다.

[Design] ImageCard 배우 명단 출력 제거

---

server/src/main/java/MuDuck/MuDuck/map/entity/AvgEntity.java
server/src/main/java/MuDuck/MuDuck/map/mapper/MapMapper.java

#37 
1. 지도 mapper 소수점 자릿수 표현 수정

[Fix] 지도 관련 mapper 수정

---

server/src/main/java/MuDuck/MuDuck/board/entity/Board.java
server/src/main/resources/db/data.sql

게시글 조회 시 카테고리를 반환 못해주는 이슈가 발생함
Board Entity에 연관관계 매핑을 잘못해주었었음
[Fix] 게시글 조회 시 카테고리 반환을 못해주는 이슈를 해결 #134

[Fix] 게시글 조회 시 카테고리 반환을 못해주는 이슈를 해결 #134

---

client/src/components/WriterInfo.jsx
client/src/routes/Mypage/MyInformation.jsx
client/src/routes/Post/CommentList.jsx
client/src/routes/Post/PostPage.jsx
client/src/routes/PostAdd/PostAddPage.jsx

- #192 
로그인 여부에 따라 댓글창과 작성하기 상태를 변경하고 뒤로가기 기능을 개선했습니다.

[Fix] 커뮤니티 상세 페이지 개선

---

client/src/components/Editors.jsx
client/src/components/MeatballsMenu.jsx
client/src/routes/Main/MainPage.jsx
client/src/routes/Plays/PlaysPage.jsx
client/src/styles/GlobalStyle.js

- #193
기본 폰트 변경 등 서비스 디자인을 개선했습니다.

[Design] 서비스 디자인 개선

---

client/src/components/Editors.jsx

- #53 
input창 내의 텍스트 색상을 변경했습니다.

[Design] 게시물 작성 페이지 input창 텍스트 색상 변경

---

client/src/routes/Play/AboutMusical.jsx
client/src/routes/Play/PlayPage.jsx

- #201 
- 리뷰쓰러가기에 커서 포인터적용
- 배우 프로필이미지 정렬 변경
- 배우 더보기 모달창 백그라운드 클릭시 모달 닫힘 추가
- 배우 더보기 모달창 마진조정

[Design] 공연상세페이지 세부 디테일 수정사항 개선

---

client/src/routes/Myinfo/MyinfoPage.jsx
client/src/routes/Root.jsx

[Design] toastify UI 적용

---

client/src/routes/Myinfo/MyinfoPage.jsx
client/src/routes/Root.jsx

Close #205 
- #205 
토스트디자인 세부설정

[Design] 토스트디자인 세부설정

---

client/src/components/Editors.jsx
client/src/components/Input.jsx

- #208 
close #208 
일부유저에게 게시글작성 TextArea 높이가 변경되는 현상수정

[Fix] 일부유저에게 게시글작성 TextArea 높이가 변경되는 현상수정

---

server/src/main/java/MuDuck/MuDuck/map/repository/MapRepository.java
server/src/main/resources/db/data.sql

#37 
1. mapRepository Query 문 수정
2. 더미데이터 수정
리팩토링을 어떻게 진행할 것인가?

[Fix] mapRepository 쿼리문 수정 & 더미데이터 변경

---

client/src/components/Map/Map.jsx
client/src/routes/Nearby/NearbyPage.jsx
client/src/routes/Play/AboutMusical.jsx
client/src/routes/Root.jsx
client/src/styles/GlobalStyle.js

- #191 
ux, ui 개선
phone 값이 없을 시 공백으로 들어가 서버에서 받아 들여지지 않아 null 값으로 변경
필요 없는 toast 경고 창 삭제

[Refactor] Feature/near by refactoring

---

client/src/routes/Nearby/NearbyPage.jsx

[Fix] Feature/near by refactoring

---

server/src/main/java/MuDuck/MuDuck/auth/config/SecurityConfiguration.java
server/src/main/java/MuDuck/MuDuck/auth/handler/OAuth2AuthenticationFailureHandler.java
server/src/main/java/MuDuck/MuDuck/auth/handler/OAuth2AuthenticationSuccessHandler.java
server/src/main/java/MuDuck/MuDuck/member/dto/MemberDto.java
server/src/main/java/MuDuck/MuDuck/token/controller/RefreshTokenController.java
server/src/main/resources/application-local.yml
server/src/main/resources/application.yml
server/src/main/resources/db/data.sql

#37 
1. antMatchers 수정
2. 로그인 성공 실패 핸들러 수정
3. yml 수정

[Fix] security antMatchers 수정&로그인  성공 실패 핸들러 수정& yml 수정

---

server/src/main/java/MuDuck/MuDuck/auth/config/SecurityConfiguration.java

antMatchers 추가

---

server/src/main/resources/application-local.yml
server/src/main/resources/application.yml

[Fix] yml 수정

---

server/src/main/resources/application.yml
server/src/test/resources/application-local.yml
server/src/test/resources/application.yml

[Fix] yml 환경변수 설정

---

client/src/components/Map/Map.jsx
client/src/routes/Nearby/NearbyPage.jsx
client/src/utile/withinOneKm.js

지도 장소 등록 시 1km 이내의 장소만 등록할 수 있게 했습니다.
지도 검색 결과의 페이지네이션 버그를 수정했습니다.

[Feat] 1km 이내의 장소만 등록

---

client/src/components/Cards.jsx
client/src/components/MeatballsMenu.jsx
client/src/routes/Main/PopularPosts.jsx
client/src/routes/Myinfo/MyinfoPage.jsx
client/src/routes/Mypage/MyInformation.jsx

- #193 
메인페이지 게시글 카드 디자인을 조정했습니다.
또한 닉네임 정규식 검사 시 대문자도 체크할 수 있도록 추가했습니다.

[Design] 메인페이지 게시글 카드 디자인 조정
